### ISSUE TITLE
Preview doesn't render local images

### ISSUE THREAD

**Issue by skiprca** [lukakerr/twig#25]
Hello!

I can't find a way for local image to render properly in preview window.

I use three files for testing:

```
/Users/johndoe/tmp/aaa.md 
/Users/johndoe/tmp/aaa.png
/Users/johndoe/tmp/aaa/aaa.png - for testing relative subfolder
```
Nothing of the following seems to work: 
```
![test png 1](aaa.png)
![test png 2](aaa/aaa.png)
![test png 3](file:///Users/johndoe/tmp/aaa.png)
<img src="aaa.png" alt="test png 4">
<img src="aaa/aaa.png" alt="test png 5">
```
Web link works as it should:
```
![web png](https://johndoe.com/aaa.png)
```

I tried to preview same aaa.md in MacDown and it works for all cases.

Am I missing something?

Thank you for your time,
Aljoša

**Comment by lukakerr** [comment]
This is a known bug/missing feature. Unfortunately `WKWebView` doesn't make it easy to include local assets (including images). I believe MacDown is using the old `WebView` which makes this easier

**Comment by skiprca** [comment]
Thank you for a fast response. Do you plan to implement this in near future or should I dig in myself? ;)

Regards,
Aljoša

**Comment by lukakerr** [comment]
@skiprca If your keen then definitely have a go to try and fix it, thanks! I was planning on getting to it some time in the future, but haven't had much time to work on it recently unfortunately

**Comment by lukakerr** [comment]
I've begun work on this in #32, but as you can read in the PR, there is a small problem i'm facing. If I can't solve it in the next few days, i'll merge the PR in anyway.

**Comment by noestreich** [comment]
Just stumbled on entry #32 after unsuccessfully trying to get image preview to load. Glad you just started implementing it. 

If i may add: 
- Since you just showed markdown-syntax in your screenshot-preview, it would be great if <img src=""> would also be supported. 
- i would greatly appreciate an easy possibility to insert an empty markdown image-tag  `![]()` with a shortcut. [Macdown](https://macdown.uranusjr.com/) uses <kbd>Command</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd>
and the last image-related addidion: 
- A quick and easy way to define image size (really important for PDF-Export) would be great. Something similar was [already wished for](https://github.com/MacDownApp/macdown/issues/677#issue-183610750) for macdown before they ceased development. I quote: "If there is a way to implement the syntax `![](pic/location/url =200x)` like Mou, or just add an alternative way of `cmd + shift + i` to input `<img src="" width="">` directly." 
Thanks.

**Comment by lukakerr** [comment]
@noestreich regarding the feature wish list:

- `<img src="">` tags are supported for rendering images in #32 
- I will definitely add a shortcut for markdown images
- In #32 you can specify the width and height using the HTML `<img>` tags. I don't plan to support setting width/height using the markdown syntax since CommonMark and GitHub Flavored Markdown don't support it either. Perhaps instead I will implement the shortcut mentioned to insert `<img src="" width="">` directly

**Comment by noestreich** [comment]
Perfect and reasonable reply all around. Thanks for the fast feedback! Looking forward to use the image preview.

**Comment by lukakerr** [comment]
The issue in #32 has been fixed! A good nights sleep always resolves any problems. I also implemented both markdown and HTML image shortcuts.

- For a markdown image, the shortcut is <kbd>Command</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd>
- For a HTML image, the shortcut is <kbd>Control</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd>

These new shortcuts and the new local image feature will be included in the next release.
