### ISSUE TITLE
If typing fast cursor goes between characters

### ISSUE THREAD

**Issue by jonathanobino** [lukakerr/twig#26]
While trying the app I was typing a bunch of chars really fast and suddenly the cursor went backwodrd(1 char in the beginning, the more chars I've entered more the cursor goes backward)

**Comment by jonathanobino** [comment]
[Here it's the screen recording](https://media.giphy.com/media/wIkjrWaZBoJwTyOLfU/source.mp4)

**Comment by lukakerr** [comment]
I believe this was caused by the slowish syntax highlighting, and I indeed could reproduce it. This should be fixed in cfbfaab as I can't reproduce the issue anymore, and will be included in the next release.

If you still experience this problem after the next release, feel free to re-open this issue.
