### ISSUE TITLE
Filename with square brackets

### ISSUE THREAD

**Issue by noestreich** [lukakerr/twig#33]
My File `[Testdatei].md` can be opened fine, but is (after the first autosave?) shown as `%5BTestdatei%5D.md` in the titlebar, the tabs and the sitebar: 

<img width="829" alt="bildschirmfoto 2019-02-19 um 22 28 26" src="https://user-images.githubusercontent.com/309419/53048840-f82d4a80-3495-11e9-97cd-c10546f0278c.png">

Also, it seems that Twig is trying to save the file under the renamed name and fails: 

<img width="409" alt="bildschirmfoto 2019-02-19 um 22 29 05" src="https://user-images.githubusercontent.com/309419/53048830-f19ed300-3495-11e9-8717-a71e9583e2df.png">

**Comment by lukakerr** [comment]
This has been fixed in https://github.com/lukakerr/twig/commit/cf771cc08cd8187113d2ec1155047657390e4281#diff-6f86f6866c153e6ba046ba4f827ac759R25. Filenames with non alphabetic characters weren't being decoded properly, and now should be. The fix just hasn’t been put into a release yet. 

I’ll close this issue for now, but if you still experience this problem after the next release, feel free to re-open this issue.
