### ISSUE TITLE
Feature Request: Markdown Cheatsheet in Client

### ISSUE THREAD

**Issue by Kevin-Chung** [lukakerr/twig#34]
It would be nice to be able to have a window, popup, panel, or something that can show markdown quick notes similar to the ones found here:
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

**Comment by lukakerr** [comment]
Great idea! This has been added in 1ec24b6. I made it an extra seperate window that can be minimized and resized so that it can be viewed simultaneously while typing. It can be viewed by going to View > Show Reference, or by pressing `⌘ .`

I also only added code snippets, and not rendered output. I felt that having the rendered output would cause the reference to be way too long to be useful.

It will be included in the next release. If there are any extra things you want in it, feel free to open a new issue once it is released.
