### ISSUE TITLE
Why establish the program a connection to Cloudflare.com ? 

### ISSUE THREAD

**Issue by F3000** [lukakerr/twig#40]
Here is a screenshot from LuLu Firewall:

<img width="742" alt="bildschirmfoto 2019-03-01 um 22 23 47" src="https://user-images.githubusercontent.com/8161283/53667363-169efd00-3c71-11e9-958f-18a65bb0abbf.png">

**Comment by lukakerr** [comment]
It's to fetch CDN assets for KaTeX, which provides latex in markdown support. You can view the exact lines here:

https://github.com/lukakerr/twig/blob/3a98986d544ddf7df55a5248d7be19937807dfb5/Twig/Models/HTML.swift#L51-L53

I plan to make these assets local sometime in the future so they don't need to be downloaded.

**Comment by F3000** [comment]
ok. thanks for explaining 👍

**Comment by captchanotfun** [comment]
```
Bad: <script src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.10.0-rc/katex.min.js"></script>
Good: <script src="https://cdn.jsdelivr.net/npm/katex@0.10.0-rc.1/dist/katex.min.js"></script>
```
([from](https://github.com/go-gitea/gitea/issues/3445))

And
1. Try not to fetch 3rd party resource from the internet for security reason.
2. Add SRI check to prevent attack.
3. [You shouldn't use Cloudflare](https://github.com/privacytoolsIO/privacytools.io/issues/374#issuecomment-460077544) because [it violate](https://trac.torproject.org/projects/tor/ticket/24351) [privacy](https://notabug.org/themusicgod1/cloudflare-tor/src/master/README.md).
