### ISSUE TITLE
Exported file is illegible

### ISSUE THREAD

**Issue by ryanbloom** [lukakerr/twig#9]
In working on a new export format, I ran into the following issue: if I select a dark theme, then export HTML, the resulting file has white text and a white background. Here are a few ways I could imagine resolving it:

1. Use the same theme for previewing and exporting. In HTML, changing the background is one line of code, but it's potentially difficult for other formats.
2. Use a standard theme for exporting, regardless of the user's settings. Every export has black text, white background, and default syntax highlighting. This is probably fine if people use a separate tool for publishing anyway.
3. Let the user choose. Have a separate pop-up menu for "export theme", either in preferences or in the export window.

The theme system might need a bit of refactoring to accommodate the last two.

**Comment by lukakerr** [comment]
Good catch, I think for now the best option is just to add the background color in the HTML which i've done in 0c9c37c. 

I plan to refactor the exporting process anyway, and would like to use [Pandoc](https://pandoc.org) for exporting, which would just involve passing in a markdown or HTML file and the filetype to export to. I also think point 3 is a good idea, and since Pandoc has so many options when converting, we could incorporate a popup window where the user can choose any options they want such as the paper size, margins etc
